
package calculadora;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import java.awt.Color;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Carlos Garcia
 */
public class Calculadora extends javax.swing.JFrame {
    public ButtonsListener bl = new ButtonsListener();
    private static boolean defaultColor = true;
    
    public Float n1;
    public Float n2;
    public String operacion;
    public String cadena;
    
    public Calculadora() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.gray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        casilla = new javax.swing.JLabel();
        btnDiv = new javax.swing.JButton();
        btnMul = new javax.swing.JButton();
        btnRes = new javax.swing.JButton();
        btnAc = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnSum = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btnPun = new javax.swing.JButton();
        btnIg = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        casilla2 = new javax.swing.JLabel();
        btnDislex = new javax.swing.JButton();
        btnDalt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setBackground(new java.awt.Color(51, 255, 51));
        setForeground(new java.awt.Color(51, 255, 102));
        setResizable(false);

        casilla.setBackground(new java.awt.Color(204, 204, 255));
        casilla.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        casilla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        casilla.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        casilla.setOpaque(true);

        btnDiv.setBackground(new java.awt.Color(255, 153, 0));
        btnDiv.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnDiv.setForeground(new java.awt.Color(240, 240, 240));
        btnDiv.setText("/");
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });

        btnMul.setBackground(new java.awt.Color(255, 153, 0));
        btnMul.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnMul.setForeground(new java.awt.Color(240, 240, 240));
        btnMul.setText("X");
        btnMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulActionPerformed(evt);
            }
        });

        btnRes.setBackground(new java.awt.Color(255, 153, 0));
        btnRes.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRes.setForeground(new java.awt.Color(240, 240, 240));
        btnRes.setText("-");
        btnRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResActionPerformed(evt);
            }
        });

        btnAc.setBackground(new java.awt.Color(255, 153, 0));
        btnAc.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnAc.setForeground(new java.awt.Color(240, 240, 240));
        btnAc.setText("AC");
        btnAc.setToolTipText("");
        btnAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(0, 0, 0));
        btn8.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btn8.setForeground(new java.awt.Color(240, 240, 240));
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(0, 0, 0));
        btn9.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btn9.setForeground(new java.awt.Color(240, 240, 240));
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(0, 0, 0));
        btn5.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btn5.setForeground(new java.awt.Color(240, 240, 240));
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(0, 0, 0));
        btn7.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btn7.setForeground(new java.awt.Color(240, 240, 240));
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(0, 0, 0));
        btn6.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btn6.setForeground(new java.awt.Color(240, 240, 240));
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(0, 0, 0));
        btn4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btn4.setForeground(new java.awt.Color(240, 240, 240));
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(0, 0, 0));
        btn2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btn2.setForeground(new java.awt.Color(240, 240, 240));
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(0, 0, 0));
        btn3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btn3.setForeground(new java.awt.Color(240, 240, 240));
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btnSum.setBackground(new java.awt.Color(255, 153, 0));
        btnSum.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnSum.setForeground(new java.awt.Color(240, 240, 240));
        btnSum.setText("+");
        btnSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumActionPerformed(evt);
            }
        });

        btn1.setBackground(new java.awt.Color(0, 0, 0));
        btn1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btn1.setForeground(new java.awt.Color(240, 240, 240));
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btnPun.setBackground(new java.awt.Color(255, 153, 0));
        btnPun.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnPun.setForeground(new java.awt.Color(240, 240, 240));
        btnPun.setText(".");
        btnPun.setToolTipText("");
        btnPun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPunActionPerformed(evt);
            }
        });

        btnIg.setBackground(new java.awt.Color(255, 153, 0));
        btnIg.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnIg.setForeground(new java.awt.Color(240, 240, 240));
        btnIg.setText("=");
        btnIg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgActionPerformed(evt);
            }
        });

        btn0.setBackground(new java.awt.Color(0, 0, 0));
        btn0.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btn0.setForeground(new java.awt.Color(240, 240, 240));
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnDel.setBackground(new java.awt.Color(255, 153, 0));
        btnDel.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnDel.setForeground(new java.awt.Color(240, 240, 240));
        btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/delete (1).png"))); // NOI18N
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        casilla2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        btnDislex.setBackground(new java.awt.Color(242, 242, 242));
        btnDislex.setText("Dislexia");
        btnDislex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDislexActionPerformed(evt);
            }
        });

        btnDalt.setBackground(new java.awt.Color(242, 242, 242));
        btnDalt.setText("Daltonismo");
        btnDalt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaltActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(casilla, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(casilla2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(btnSum, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRes, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPun, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIg, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAc, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDiv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDislex)
                .addGap(18, 18, 18)
                .addComponent(btnDalt)
                .addGap(342, 342, 342))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(casilla2))
                    .addComponent(casilla, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMul, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSum, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPun, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnIg, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDalt)
                    .addComponent(btnDislex))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        setBounds(0, 0, 325, 553);
    }// </editor-fold>//GEN-END:initComponents

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        this.casilla.setText(this.casilla.getText()+"7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        
        cadena = casilla.getText();
        if(cadena.length()>0){
            cadena = cadena.substring(0, cadena.length() -1);
            casilla.setText(cadena);
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        this.casilla.setText(this.casilla.getText()+"5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        this.casilla.setText(this.casilla.getText()+"9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        this.casilla.setText(this.casilla.getText()+"8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btnAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcActionPerformed
        this.casilla.setText("");
    }//GEN-LAST:event_btnAcActionPerformed

    private void btnResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResActionPerformed
        this.n1=Float.parseFloat(this.casilla.getText());
        this.operacion = "-";
        this.casilla.setText("");
    }//GEN-LAST:event_btnResActionPerformed

    private void btnMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulActionPerformed
        this.n1=Float.parseFloat(this.casilla.getText());
        this.operacion = "*";
        this.casilla.setText("");
    }//GEN-LAST:event_btnMulActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        this.n1=Float.parseFloat(this.casilla.getText());
        this.operacion = "/";
        this.casilla.setText("");

    }//GEN-LAST:event_btnDivActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        this.casilla.setText(this.casilla.getText()+"0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnIgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgActionPerformed
        this.n2=Float.parseFloat(this.casilla.getText());

        switch(this.operacion){
            case "+": this.casilla.setText(quitarCero(this.n1+n2));
            break;
            case "-": this.casilla.setText(quitarCero(this.n1-n2));
            break;
            case "*": this.casilla.setText(quitarCero(this.n1*n2));
            break;
            case "/": this.casilla.setText(quitarCero(this.n1/n2));
            break;
        }

    }//GEN-LAST:event_btnIgActionPerformed

    private void btnPunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPunActionPerformed
        if(!(this.casilla.getText().contains("."))){
            this.casilla.setText(this.casilla.getText()+".");
        }
    }//GEN-LAST:event_btnPunActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        this.casilla.setText(this.casilla.getText()+"1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btnSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumActionPerformed
        this.n1=Float.parseFloat(this.casilla.getText());
        this.operacion = "+";
        this.casilla.setText("+");
    }//GEN-LAST:event_btnSumActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        this.casilla.setText(this.casilla.getText()+"3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        this.casilla.setText(this.casilla.getText()+"2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btnDaltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaltActionPerformed
        if (defaultColor) {
            defaultColor = false;
            btnDalt.setBackground(Color.green);
            btn1.setBackground(Color.gray);
            btn1.setForeground(Color.white);

            btn2.setBackground(Color.gray);
            btn2.setForeground(Color.white);
            btn3.setBackground(Color.gray);
            btn3.setForeground(Color.white);
            btn4.setBackground(Color.gray);
            btn4.setForeground(Color.white);
            btn5.setBackground(Color.gray);
            btn5.setForeground(Color.white);
            btn6.setBackground(Color.gray);
            btn6.setForeground(Color.white);
            btn7.setBackground(Color.gray);
            btn7.setForeground(Color.white);
            btn8.setBackground(Color.gray);
            btn8.setForeground(Color.white);
            btn9.setBackground(Color.gray);
            btn9.setForeground(Color.white);
            btn0.setBackground(Color.gray);
            btn0.setForeground(Color.white);

            btnAc.setBackground(Color.gray);
            btnDel.setBackground(Color.gray);
            btnDiv.setBackground(Color.gray);
            btnMul.setBackground(Color.gray);
            btnRes.setBackground(Color.gray);
            btnSum.setBackground(Color.gray);
            btnPun.setBackground(Color.gray);
            btnIg.setBackground(Color.gray);
            this.getContentPane().setBackground(Color.white);
        } else {
            defaultColor = true;
            btnDalt.setBackground(Color.white);
            btn1.setBackground(Color.black);
            btn1.setForeground(Color.white);

            btn2.setBackground(Color.black);
            btn2.setForeground(Color.white);
            btn3.setBackground(Color.black);
            btn3.setForeground(Color.white);
            btn4.setBackground(Color.black);
            btn4.setForeground(Color.white);
            btn5.setBackground(Color.black);
            btn5.setForeground(Color.white);
            btn6.setBackground(Color.black);
            btn6.setForeground(Color.white);
            btn7.setBackground(Color.black);
            btn7.setForeground(Color.white);
            btn8.setBackground(Color.black);
            btn8.setForeground(Color.white);
            btn9.setBackground(Color.black);
            btn9.setForeground(Color.white);
            btn0.setBackground(Color.black);
            btn0.setForeground(Color.white);

            btnAc.setBackground(new Color(255,153,0));
            btnDel.setBackground(new Color(255,153,0));
            btnDiv.setBackground(new Color(255,153,0));
            btnMul.setBackground(new Color(255,153,0));
            btnRes.setBackground(new Color(255,153,0));
            btnSum.setBackground(new Color(255,153,0));
            btnPun.setBackground(new Color(255,153,0));
            btnIg.setBackground(new Color(255,153,0));
            this.getContentPane().setBackground(Color.gray);
        }
    }//GEN-LAST:event_btnDaltActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        this.casilla.setText(this.casilla.getText()+"4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btnDislexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDislexActionPerformed
        if (defaultColor) {
            defaultColor = false;
            btnDislex.setBackground(Color.green);
            btn1.setFont(new java.awt.Font("Segoe UI Black", 0, 22));
            btn2.setFont(new java.awt.Font("Segoe UI Black", 0, 22));
            btn3.setFont(new java.awt.Font("Segoe UI Black", 0, 22));
            btn4.setFont(new java.awt.Font("Segoe UI Black", 0, 22));
            btn5.setFont(new java.awt.Font("Segoe UI Black", 0, 22));
            btn6.setFont(new java.awt.Font("Segoe UI Black", 0, 22));
            btn7.setFont(new java.awt.Font("Segoe UI Black", 0, 22));
            btn8.setFont(new java.awt.Font("Segoe UI Black", 0, 22));
            btn9.setFont(new java.awt.Font("Segoe UI Black", 0, 22));
            btn0.setFont(new java.awt.Font("Segoe UI Black", 0, 22));
            btnAc.setFont(new java.awt.Font("Segoe UI Black", 0, 22));
            btnDiv.setFont(new java.awt.Font("Segoe UI Black", 0, 22));
            btnMul.setFont(new java.awt.Font("Segoe UI Black", 0, 22));
            btnRes.setFont(new java.awt.Font("Segoe UI Black", 0, 22));
            btnSum.setFont(new java.awt.Font("Segoe UI Black", 0, 22));
            btnPun.setFont(new java.awt.Font("Segoe UI Black", 0, 22));
            btnIg.setFont(new java.awt.Font("Segoe UI Black", 0, 22));
        } else {
            defaultColor = true;
            btnDislex.setBackground(Color.white);
           btn1.setFont(new java.awt.Font("Segoe UI Black", 0, 14));
            btn2.setFont(new java.awt.Font("Segoe UI Black", 0, 14));
            btn3.setFont(new java.awt.Font("Segoe UI Black", 0, 14));
            btn4.setFont(new java.awt.Font("Segoe UI Black", 0, 14));
            btn5.setFont(new java.awt.Font("Segoe UI Black", 0, 14));
            btn6.setFont(new java.awt.Font("Segoe UI Black", 0, 14));
            btn7.setFont(new java.awt.Font("Segoe UI Black", 0, 14));
            btn8.setFont(new java.awt.Font("Segoe UI Black", 0, 14));
            btn9.setFont(new java.awt.Font("Segoe UI Black", 0, 14));
            btn0.setFont(new java.awt.Font("Segoe UI Black", 0, 14));
        }
    }//GEN-LAST:event_btnDislexActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        this.casilla.setText(this.casilla.getText()+"6");
    }//GEN-LAST:event_btn6ActionPerformed

    public String quitarCero (float resultado){
        String retorno = "";
        retorno = Float.toString(resultado);
        
        if(resultado%1 == 0){
            retorno = retorno.substring(0, retorno.length() -2);
        }
        return retorno;
    }

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAc;
    private javax.swing.JButton btnDalt;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnDislex;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnIg;
    private javax.swing.JButton btnMul;
    private javax.swing.JButton btnPun;
    private javax.swing.JButton btnRes;
    private javax.swing.JButton btnSum;
    private javax.swing.JLabel casilla;
    private javax.swing.JLabel casilla2;
    // End of variables declaration//GEN-END:variables

    private static class ButtonsListener {

        public ButtonsListener() {
        }
    }
}
